---
title: "Research"
title-block-banner: false
---

::: {style="display: flex; justify-content: space-between;"}
<!-- Publications Column -->

::: {style="flex: 1; padding-right: 20px; margin-top: -34px;"}
## Publications

[Bosch-Rosa, C.](https://www.boschrosa.com/){.black-link}, [Gonzalez-Fernandez, P.](https://www.pgonzalezfernandez.com/){.black-link} and Meissner, T. (2025)["Direct Elicitation of Parametric Belief Distributions: An application to inflation expectations"](https://doi.org/10.1016/j.jebo.2025.106947), **Journal of Economic Behavior and Organization**: 233, 106947

Flagner S., Meissner, T., Künn, S. Eichholtz, P., Kok, N., Kramer, R., van Marken-Lichtenbelt, W., Ly, C. and Guy Plasqui (2025)["The impact of indoor carbon dioxide on human cognition, behavior and metabolic health"](https://doi.org/10.1016/j.indenv.2025.100074) **Indoor Environments**: 100074 

Meissner, T., Gassmann, X., Faure, C. and Schleich, J. (2023): ["Individual characteristics associated with risk and time preferences - A multi-country representative survey"](https://link.springer.com/content/pdf/10.1007/s11166-022-09383-y.pdf), **Journal of Risk and Uncertainty**

Schleich, J., Gassmann, X., Meissner T. and Faure, C. (2023): ["Making the factors underlying the implicit discount rate tangible"](https://doi.org/10.1016/j.enpol.2023.113563) **Energy Policy**: 177, 113563

Meissner, T. and [Pfeiffer, P.](https://sites.google.com/view/philipppfeiffer/){.black-link} (2022) ["Measuring Preferences Over the Temporal Resolution of Consumption Uncertainty"](https://doi.org/10.1016/j.jet.2021.105379), **Journal of Economic Theory**: 200, 105379.

Ahrens, S., [Bosch-Rosa, C.](https://www.boschrosa.com/){.black-link} and Meissner T. (2022) ["Intertemporal Consumption and Debt Aversion: A Replication and Extension"](https://link.springer.com/content/pdf/10.1007/s40881-022-00118-y.pdf), **Journal of the Economic Science Association**

Schleich, J., Faure, C. and Meissner, T. (2021) ["Adoption of retrofit measures among homeowners in EU countries: The effects of access to capital and debt aversion"](https://www.sciencedirect.com/science/article/pii/S0301421520307369), **Energy Policy**: 149, 112025.

[Bosch-Rosa, C.](https://www.boschrosa.com/){.black-link} and Meissner, T. (2020) ["The One Player Guessing Game: A diagnosis on the relationship between equilibrium play, stated beliefs, and best responses"](http://doi.org/10.1007/s10683-020-09642-2), **Experimental Economics**: 23, 1129--1147

Schleich, J., Gassmann, X., Meissner, T. and Faure, C. (2019) ["A large-scale test of the effects of time discounting, risk aversion, loss aversion and present bias on household adoption of energy efficient technologies."](https://doi.org/10.1016/j.eneco.2018.12.018) **Energy Economics**: 80, 377-393.

[Bosch-Rosa, C.](https://www.boschrosa.com/){.black-link}, Meissner, T. and Bosch-Domenech, A. (2018): ["Cognitive Bubbles"](https://link.springer.com/article/10.1007/s10683-017-9529-0), **Experimental Economics**: 21, 1, 132-153.

Meissner, T. and [Rostam-Afschar, D.](https://rostam-afschar.de/){.black-link} (2017): ["Learning Ricardian Equivalence."](https://www.sciencedirect.com/science/article/pii/S0165188917301495) **Journal of Economic Dynamics and Control**: 82, 273-288.

Meissner, T. (2016). ["Intertemporal consumption and debt aversion: an experimental study."](https://link.springer.com/article/10.1007/s10683-015-9437-0) **Experimental Economics**: 19, 2, 281-298.

Schleich, J., Gassmann, X., Faure, C. and Meissner, T (2016): ["Making the Implicit Explicit: A Look Inside Implicit Discount Rates."](https://www.sciencedirect.com/science/article/pii/S0301421516304050) **Energy Policy**: 97, 321-331.
:::

<!-- Working Papers Column -->

::: {style="flex: 1; padding-left: 20px; margin-top: -34px;"}
## Working Papers

["Tricked into trouble: Deception, threat, and coercion in exploitative labor relations"](http://cris.maastrichtuniversity.nl/ws/portalfiles/portal/276159447/RM25007.pdf), with Max Schmitt, Gewei Cao and Hannes Rusch


["Debt Aversion: Theory and Measurement"](https://arxiv.org/pdf/2207.07538.pdf), with [David Albrecht](https://da-lbrecht.github.io/){.black-link}. [ [Replication Package] ](https://osf.io/7sm2f/?view_only=8466d18f89d1492b81baf7ec84ef12ea){.black-link}


["The debt aversion survey module: An experimentally validated tool to measure individual debt aversion"](https://arxiv.org/pdf/2211.02742.pdf), with [David Albrecht](https://da-lbrecht.github.io/){.black-link}. [ [Replication Package] ](https://osf.io/7sm2f/?view_only=8466d18f89d1492b81baf7ec84ef12ea){.black-link}

### Work in Progress

"Does the Real Interest Rate Really Matter for Consumption?" with [Bosch-Rosa, C.](https://www.boschrosa.com/){.black-link} and Baptiste Massenot

"Modafinil improves cognition and increases risk taking in healthy human subjects” with Hyemi
Jin, Matthias Wibral, Anke Sambeth and Arjan Blokland




:::
:::
