project:
  type: website
  output-dir: ..
  execute-dir: project
  
  
website:
  favicon: profil.png
  page-navigation: true
  #title: "Thomas Meissner"
  google-analytics:
    tracking-id: "G-WEL4YD4BS5"
    anonymize-ip: false

  navbar:
    right:
    
      - text: "About me"
        href: index.qmd
        
      - text: "Research"
        href: research/index.qmd

      - text: "CV"
        href: CV.pdf

      - text: "M-BEES & M-BEPS"
        href: https://sites.google.com/view/mbees-mbeps/home

format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: false
    format:


    


