project:
  type: website
  output-dir: ..
  execute-dir: project
  
  
website:
  page-navigation: true
  title: "Thomas Meissner"

  navbar:
    right:
    
      - text: "About me"
        href: index.qmd
        
      - text: "Research"
        href: research/index.qmd

      - text: "Talks"
        href: talks/index.qmd

      - text: "Blog"
        href: blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    head-includes:
      - '<link rel="icon" type="image/x-icon" href="favicon.ico">'


