project:
  type: website
  output-dir: ..
  execute-dir: project
  title: "tmeissner.com"
  resources:
    - "tools/beta.html"
    - "tools/beta.qsf"

website:
  favicon: profile.png
  page-navigation: true
  google-analytics:
    tracking-id: "G-WEL4YD4BS5"
    anonymize-ip: false

  navbar:
    right:
      - text: "About me"
        href: index.qmd
      - text: "Research"
        href: research/index.qmd
      - text: "Tools"
        href: tools/index.qmd
      - text: "CV"
        href: CV.pdf
      - text: "M-BEES & M-BEPS"
        href: https://sites.google.com/view/mbees-mbeps/home

format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: false
    html-math-method: katex
    self-contained: true
    allow-html: true
    include-in-header:
      - text: |
          <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>