project:
  type: website
  output-dir: ..
  execute-dir: project
  
  
website:
  favicon: favicon.ico
  page-navigation: true
  title: "Thomas Meissner"
  google-analytics:
    tracking-id: "G-WEL4YD4BS5"

  navbar:
    right:
    
      - text: "About me"
        href: index.qmd
        
      - text: "Research"
        href: research/index.qmd

      - text: "Talks"
        href: talks/index.qmd

      - text: "Blog"
        href: blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    


