---
title: "Tools"
title-block-banner: false
format:
  html:
    include-in-header:
      - text: |
          <script src="https://cdnjs.cloudflare.com/ajax/libs/jstat/1.9.4/jstat.min.js"></script>
          <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
---
## Belief Distribution Elicitation Tool

Here you can find our method to elicit parameteric (beta) belief distributions, as described in ["Direct Elicitation of Parametric Belief Distributions: An application to inflation expectations"](https://doi.org/10.1016/j.jebo.2025.106947), with [Pedro Gonzalez-Fernandez](https://www.pgonzalezfernandez.com/){.black-link} and [Ciril Bosch-Rosa](https://www.boschrosa.com/){.black-link}.

- [oTree implementation](https://github.com/TGKMeissner/BetaBeliefs.git){target="_blank"} access github repository with the oTree implementation.
- [Qualtrics implementation](beta.qsf){download="beta.qsf"} download .QSF file.



::: {.html}
<div id="beta-belief-tool-container"></div>
<script>
  const betaBeliefTool = document.createElement("iframe");
  betaBeliefTool.id = "beta-belief-tool";
  betaBeliefTool.src = "beta" + "1.html";
  betaBeliefTool.style.width = "100%";
  betaBeliefTool.style.height = "720px";
  betaBeliefTool.style.border = "none";
  betaBeliefTool.setAttribute("scrolling", "no");
  document.getElementById("beta-belief-tool-container").appendChild(betaBeliefTool);
</script>
:::
